# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Weikun Han's Website
subtitle: ''
description: 'May world peace, without pride and prejudice 愿世界和平，没有骄傲和偏见'
keywords: 'Weikun Han'
author: Weikunu Han
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://weikunhan.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - images/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 'git'
  repo: https://github.com/weikunhan/weikunhan.github.io/
  branch: master

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-volantis

# Replace theme configs
theme_config:
  ## The style config:
  style:
    navbar:
      height: 64px
      width: auto 
      effect: [shadow, blur, floatable] 
    sidebar:
      effect: [shadow, blur, floatable] 
    fontsize:
      root: 18px
      h1: 1.625rem
      h2: 1.375rem
      h3: 1.25rem
      h4: 1.125rem
      h5: 1rem
      h6: 1rem
      body: 1rem
      list: .9375rem
      meta: .875rem
      code: .8125rem
      footnote: .75rem
    fontfamily:
      logofont:
        fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'Varela Round'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
        weight: normal
        style: normal
      bodyfont:
        fontfamily: 'UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'UbuntuMono'
        url: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/fonts/times_new_roman.ttf
        weight: normal
        style: normal
        offset: 0.1rem # Correct baseline for zh-CN
      codefont:
        fontfamily: 'Menlo, UbuntuMono, Monaco'
        name: 'Monaco'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
        weight: normal
        style: normal   
  ## The cover config
  cover:
    scheme: docs
    display:
      home: true
      archive: true
      others: true 
    logo: 
    title: Weikun Han
    subtitle: '「Computer Vision Scientist」'
    search: 'Search...'
    features:
      - name: Home
        icon: fas fa-home
        url: /
      - name: Publications
        icon: fas fa-file-alt
        url: /publications
      - name: Projects
        icon: fas fa-robot
        url: /projects
      - name: Courses
        icon: fas fa-graduation-cap
        url: /courses
      - name: Awards
        icon: fas fa-trophy
        url: /awards
      - name: Blogs
        icon: fas fa-blog
        url: /blogs
  ## The navbar config
  navbar:
    logo: 
      img: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/images/new_weikun_han_web_1.png
      icon: 
      title: 
    ## Move to source/_data/menu.yml
    #menu: 
    search: 'Search...'
  ## The layout config move to source/_data/layout.yml
  ##layout:
  ## The meto library
  meta:
    author:
      avatar: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/images/weikun_han_1.png
      name: Weikun Han
      url: https://weikunhan.github.io/
    date:
      icon: fas fa-calendar-alt
      title: 'Created on: '
      format: 'll' 
    updated:
      icon: fas fa-edit
      title: 'Update on：'
      format: 'll' 
  ## The widget config move to source/_data/wigdet.yml
  ##widget:
  ## The footer config
  footer:
    layout: [aplayer, social, info, copyright]
    social:
      - icon: fas fa-envelope-square
        url: mailto:weikunhan@gmail.com
      - icon: fas fa-pen-square
        url: https://www.zhihu.com/people/weikunhan
      - icon: fab fa-github-square
        url: https://github.com/weikunhan/
      - icon: fab fa-linkedin
        url: https://www.linkedin.com/in/weikunhan/
      - icon: fab fa-medium
        url: https://medium.com/@weikunhan300
      - icon: fas fa-id-card
        url: https://scholar.google.com/citations?user=MOfRj_YAAAAJ&hl=en/
      - icon: fas fa-file-download
        url: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/resumes/curriculum_vitae_1.pdf
    copyright: '[Copyright © 2020 Weikun Han](https://weikunhan.github.io)'
    br: '<br>'
  ## The plugins config
  plugins:
    backstretch:
      enable: true
      js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
      position: cover       
      shuffle: true         
      duration: 30000
      fade: 1500            
      images:               
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_A1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_A2.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_B1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_C1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_D1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_D2.jpeg
    aplayer:
      enable: true
      js:
        - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
        - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
      server: tencent   
      type: search    
      id: Mozart Lang Lang
      fixed: false      
      theme: '#1BCDFC'  
      autoplay: true   
      order: random       
      loop: all        
      volume: 0.3      
      list_max_height: 340px 
      list_folded: true