# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Weikun Han's Website
subtitle: ''
description: 'May world peace, without pride and prejudice 愿世界和平，没有骄傲和偏见'
keywords: 'Weikun Han'
author: Weikunu Han
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://weikunhan.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - images/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 'git'
  repo: https://github.com/weikunhan/weikunhan.github.io/
  branch: master

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Replace theme configs
theme_config:
  ## The navbar config
  navbar:
    logo: 
      img: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/images/new_weikun_han_web_1.png
      icon: 
      title: 
    menu:
      - name: Home
        icon: fas fa-home
        url: /
      - name: Projects
        icon: fas fa-robot
        url: /projects
      - name: Publications
        icon: fas fa-file-alt
        url: /publications
      - name: Courses
        icon: fas fa-graduation-cap
        url: /courses
      - name: Awards
        icon: fas fa-trophy
        url: /awards
      - name: Blogs
        icon: fas fa-book
        url: /blogs
    search: 'Search...'
  ## The cover config
  cover:
    height_scheme: half # full, half
    layout_scheme: focus # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
    display:
      home: true
      archive: true
      others: true 
    title: Weikun Han
    subtitle: '「Computer Vision Scientist」'
    search: 'Search...'
    features:
      - name: Home
        icon: fas fa-home
        url: /
      - name: Projects
        icon: fas fa-robot
        url: /projects
      - name: Publications
        icon: fas fa-file-alt
        url: /publications
      - name: Courses
        icon: fas fa-graduation-cap
        url: /courses
      - name: Awards
        icon: fas fa-trophy
        url: /awards
      - name: Blogs
        icon: fas fa-blog
        url: /blogs
  ## The layout config move to source/_data/layout.yml
  article:
    preview:
      scheme: landscape # landscape
      pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
      auto_title: false # false, true
      auto_excerpt: false # false, true
      line_style: solid # hidden, solid, dashed, dotted
      author: false # true, false
      readmore: auto # auto, always
  ## The meto library
  sidebar:
    widget_library:
      blogger:
        class: blogger
        display: [desktop, mobile]
        avatar: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/images/weikun_han_1.png
        shape: rectangle
        url: /
        title: Weikun Han
        subtitle: '「Computer Vision Scientist」'
        jinrishici: false
        social:
          - icon: fas fa-envelope-square
            url: mailto:weikunhan@gmail.com
          - icon: fas fa-pen-square
            url: https://www.zhihu.com/people/weikunhan
          - icon: fab fa-github-square
            url: https://github.com/weikunhan/
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/in/weikunhan/
          - icon: fab fa-medium
            url: https://medium.com/@weikunhan300
          - icon: fas fa-id-card
            url: https://scholar.google.com/citations?user=MOfRj_YAAAAJ&hl=en/
          - icon: fas fa-file-download
            url: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/resumes/curriculum_vitae_4.pdf
      toc:
        class: toc
        display: [desktop, mobile] 
        header:
          icon: fas fa-list
          title: Contents
        list_number: false
        min_depth: 2
        max_depth: 5
  ## The footer config
  site_footer:
    layout: [aplayer, social, info, analytics, copyright]
    social:
      - icon: fas fa-envelope-square
        url: mailto:weikunhan@gmail.com
      - icon: fas fa-pen-square
        url: https://www.zhihu.com/people/weikunhan
      - icon: fab fa-github-square
        url: https://github.com/weikunhan/
      - icon: fab fa-linkedin
        url: https://www.linkedin.com/in/weikunhan/
      - icon: fab fa-medium
        url: https://medium.com/@weikunhan300
      - icon: fas fa-id-card
        url: https://scholar.google.com/citations?user=MOfRj_YAAAAJ&hl=en/
      - icon: fas fa-file-download
        url: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/resumes/curriculum_vitae_4.pdf
    analytics: >
      <span id="lc-sv">Total visits <span id='number'><i class="fas fa-circle-notch fa-spin fa-fw" aria-hidden="true"></i></span> times</span>
    copyright: 'Copyright © 2020 Weikun Han'
    br: '<br>'
  ## The plugins config
  plugins:
    backstretch:
      enable: true
      js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
      position: cover       
      shuffle: true         
      duration: 30000
      fade: 1500            
      images:               
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_A1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_A2.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_B1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_C1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_D1.jpeg
        - https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/wallpapers/abstract_D2.jpeg
    aplayer:
      enable: true
      js:
        - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
        - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
      server: tencent   
      type: search    
      id: Mozart Lang Lang
      fixed: false      
      theme: '#1BCDFC'  
      autoplay: true   
      order: random       
      loop: all        
      volume: 0.3      
      list_max_height: 320px 
      list_folded: true
    darkmodejs:
      enable: true
  ## The customized rightmenu
  rightmenu:
    enable: false
  ## The style config:
  custom_css:
    navbar:
      height: 64px
      width: auto 
      effect: [shadow, blur, floatable] 
    sidebar:
      effect: [shadow, blur, floatable]
    #fontsize:
    #  root: 16px
    #  h1: 1.5rem
    #  h2: 1.4rem
    #  h3: 1.3rem
    #  h4: 1.2rem
    #  h5: 1.0rem
    #  h6: 1.0rem
    #  body: 1.1rem
    #  list: 1.1rem
    #  meta: 0.9rem
    #  code: 0.9rem
    #  footnote: .75rem
    fontfamily:
      logofont:
        fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'Varela Round'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
        weight: normal
        style: normal
      bodyfont:
        fontfamily: 'UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'UbuntuMono'
        url: https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/fonts/times_new_roman.ttf
        weight: normal
        style: normal
        offset: 
      codefont:
        fontfamily: 'Menlo, UbuntuMono, Monaco'
        name: 'Monaco'
        url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
        weight: normal
        style: normal   